# We test each method for building LaTeX in a separate job.
jobs:
  include:
      # Each script call is a separate job.
    - script: chmod +x $TRAVIS_BUILD_DIR/test/compile-1.sh && $TRAVIS_BUILD_DIR/test/compile-1.sh
    - script: chmod +x $TRAVIS_BUILD_DIR/test/compile-2.sh && $TRAVIS_BUILD_DIR/test/compile-2.sh
    - language: r
      sudo: true
      latex: false
      pandoc: false
      warnings_are_errors: false
      script: chmod +x $TRAVIS_BUILD_DIR/test/compile-3.sh && $TRAVIS_BUILD_DIR/test/compile-3.sh

cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache/Tectonic
    - /tmp/texlive
    - $HOME/.texlive
    - packages
