# We test each method for building LaTeX in a separate job.
language: generic

jobs:
  include:
    # Each - starts a separate job
    - services: docker
      sudo: required
      script: chmod +x $TRAVIS_BUILD_DIR/test/tectonic-docker-test.sh && $TRAVIS_BUILD_DIR/test/tectonic-docker-test.sh
    - script: chmod +x $TRAVIS_BUILD_DIR/test/tectonic-miniconda-test.sh && $TRAVIS_BUILD_DIR/test/tectonic-miniconda-test.sh
    - script: chmod +x $TRAVIS_BUILD_DIR/test/texlive-test.sh && $TRAVIS_BUILD_DIR/test/texlive-test.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/miniconda
    - $HOME/.cache/Tectonic

# Disable this test because it's broken and nobody uses it anyway
#    - stage: tinytex
#      language: r
#      sudo: true
#      latex: false
#      pandoc: false
#      warnings_are_errors: false
#      install: echo "The install step is required but does nothing now."
#      script: chmod +x $TRAVIS_BUILD_DIR/test/tinytex-test.sh && $TRAVIS_BUILD_DIR/test/tinytex-test.sh
#      cache:
#        directories:
#          - packages
#          - /tmp/texlive
#          - $HOME/.texlive
#          - $HOME/.TinyTex