notifications:
  email: false
jobs:
  include:
#    - stage: install
    - script: chmod +x $TRAVIS_BUILD_DIR/texlivepdflatex/texlive_install.sh && $TRAVIS_BUILD_DIR/texlivepdflatex/texlive_install.sh
#    - stage: compile
#      script: ./2-texlive-pdflatex/compile.sh